trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'api-mottu'
  dockerRegistry: 'sprint4acr.azurecr.io'

steps:
# 1. Instala o .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Instalar .NET 8 SDK'

# 2. Restore
- script: dotnet restore
  displayName: 'Restore'

# 3. Build
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

# 4. Testes (Sprint 4 exige testes)
- script: dotnet test --configuration $(buildConfiguration) --no-build
  displayName: 'Testes Unit√°rios'

# 5. Publicar artefato
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artefatos'

# 6. Login no ACR
- task: Docker@2
  displayName: 'ACR Login'
  inputs:
    command: login
    containerRegistry: 'sprint4acr'   # service connection no Azure DevOps

# 7. Build Docker
- task: Docker@2
  displayName: 'Build da imagem Docker'
  inputs:
    command: build
    Dockerfile: 'Dockerfile'
    tags: |
      $(dockerRegistry)/$(imageName):$(Build.BuildId)

# 8. Push Docker
- task: Docker@2
  displayName: 'Push da imagem para ACR'
  inputs:
    command: push
    tags: |
      $(dockerRegistry)/$(imageName):$(Build.BuildId)

# 9. Publicar metadata para CD
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'deploy-info'
    publishLocation: 'Container'

