trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'mottu-api'

steps:
# 1. Instala o .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Instalar .NET 8 SDK'

# 2. Restore da solution
- script: dotnet restore sprint_4/CSharp/*.sln
  displayName: 'Restore Solution'

# 3. Build
- script: dotnet build sprint_4/CSharp/*.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

# 4. Testes
- script: dotnet test sprint_4/CSharp/*.sln --configuration $(buildConfiguration) --no-build
  displayName: 'Run Tests'

# 5. Login no ACR
- task: Docker@2
  displayName: 'ACR Login'
  inputs:
    command: login
    containerRegistry: 'acr-mottu-new-connection'

# 6. Build Docker
- task: Docker@2
  displayName: 'Build da imagem Docker'
  inputs:
    containerRegistry: 'acr-mottu-new-connection'
    repository: 'mottu-repository'
    command: build
    Dockerfile: 'sprint_4/CSharp/Dockerfile'
    tags: |
      $(Build.BuildId)

# 7. Push Docker
- task: Docker@2
  displayName: 'Push da imagem para ACR'
  inputs:
    containerRegistry: 'acr-mottu-new-connection'
    repository: 'mottu-repository'
    command: push
    tags: |
      $(Build.BuildId)

# 8. Gerar arquivo contendo a TAG da imagem
- script: echo $(Build.BuildId) > $(Build.ArtifactStagingDirectory)/imageTag.txt
  displayName: 'Gerar arquivo de tag para CD'

# 9. Publicar artefato para o CD
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'deploy-info'
    publishLocation: 'Container'
  displayName: 'Publicar artefatos'
